...
title: Tim Hagmann - Website
description: Personal data science website
url: https://greenore.github.io
author: Tim Hagmann
twitter:
    username: timhagmann
logo: /images/advanced_data_science.jpg
social:
  name: Tim Hagmann
  links:
    - https://twitter.com/timhagmann
    - https://www.facebook.com/tim.hagmann
    - https://www.linkedin.com/in/timhagmann/
    - https://plus.google.com/u/0/108308395320262995730
    - https://github.com/greenore
gems:
  - jekyll-seo-tag
...
